apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voice-platform-e2e
  namespace: argocd
  labels:
    environment: e2e
    app: voice-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rashesh91/ml-inference-gitops.git
    targetRevision: HEAD
    path: applications/voice-platform
    helm:
      releaseName: voice-e2e
      valueFiles:
        - values.yaml
        - values-e2e.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: voice-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers: [/spec/volumeClaimTemplates]
    - group: ""
      kind: ConfigMap
      name: vllm-model-config
      namespace: voice-platform
      jsonPointers:
        - /data/model_source
        - /data/minio_path
        - /data/minio_bucket
        - /data/job_id
        - /data/mlflow_run_id
